"""auto_adding_categories_for_books

Revision ID: 49ec5ea2e1a1
Revises: de2b1600bed6
Create Date: 2026-04-10 20:27:16.232801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49ec5ea2e1a1'
down_revision: Union[str, Sequence[str], None] = 'de2b1600bed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('categories', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'categories')
    # ### end Alembic commands ###
