"""auto_adding_address_to_order

Revision ID: 8a9d2dcaeffd
Revises: e3defd8a71e3
Create Date: 2026-04-10 21:57:49.602919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a9d2dcaeffd'
down_revision: Union[str, Sequence[str], None] = 'e3defd8a71e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'address')
    # ### end Alembic commands ###
