"""auto_adding_verification_the_email

Revision ID: 964b07ef8271
Revises: 2eaa10321ffc
Create Date: 2026-04-10 19:36:34.513455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '964b07ef8271'
down_revision: Union[str, Sequence[str], None] = '2eaa10321ffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verify_gmail', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verify_gmail')
    # ### end Alembic commands ###
